export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const ADD_COMPLETED_TODAY = 'ADD_COMPLETED_TODAY';
export const ADD_COMPLETED_EVERYDAY = 'ADD_COMPLETED_EVERYDAY';
export const UPDATE_TASK_STATE = 'UPDATE_TASK_STATE';
export const GET_TASK_LIST = 'GET_TASK_LIST';
